### ISSUE TITLE
module.js:472

### ISSUE THREAD

**Issue by storm134** [seiya-dev/hidive-downloader-nx#4]
** Main info: **

Script version: 1.40 (just downloaded)
Show ID: 
Episode ID: 

** Additional Info: **

C:\hidive-downloader-nx-master>node hidive.js

=== HIDIVE Downloader NX 1.4.0 ===

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\hidive-downloader-nx-master\modules'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\hidive-downloader-nx-master\hidive.js:46:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Double checked the install step's alway get this error, have tried it on 2 different machines. not sure what i am doing wrong.

**Comment by seiya-git** [comment]
Fixed in 1.5.0
