### ISSUE TITLE
Muxing fails at subtitles

### ISSUE THREAD

**Issue by Golumpa** [seiya-dev/hidive-downloader-nx#6]
** Main info: **

Script version: 1.7.0
Show ID: (not relevant)
Episode ID: (not relevant)

** Info: **

The bot seems to be getting stuck at the muxing stage with the subtitles. It seems the new feature of checking if the file is Caps or not doesn't seem to work properly. I have attached the error below.

```
(node:28186) UnhandledPromiseRejectionWarning: ReferenceError: t is not defined
    at muxStreams (/root/hidivetmp/hidive.js:512:33)
    at downloadMedia (/root/hidivetmp/hidive.js:491:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28186) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28186) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by seiya-git** [comment]
strange. can you give ids anyway?

**Comment by Golumpa** [comment]
Running on li ux, should be the latest node aswel v10.4.1

Show ID: 887
Episode ID: s01e011

**Comment by seiya-git** [comment]
write full command options
